create DATABASE PV_DATABASE;
USE DATABASE PV_DATABASE;


CREATE OR REPLACE TABLE SalesData (
order_id VARCHAR(15),
order_date DATE,
ship_date DATE,
ship_mode VARCHAR(20),
customer_name VARCHAR(30),
segment VARCHAR(20),
state VARCHAR(40),
country VARCHAR(55),
market VARCHAR(10),
region VARCHAR(30),
product_id VARCHAR(25),
category VARCHAR(20),
sub_category VARCHAR(30),
product_name VARCHAR(150),
sales NUMBER(8),
quantity NUMBER(3),
discount VARCHAR(10),
profit VARCHAR(10),
shipping_cost VARCHAR(8),
order_priority VARCHAR(10),
year NUMBER(4)
);

SELECT * FROM SalesData;
DESC TABLE SalesData;

CREATE OR REPLACE TABLE SALESDATA_FINAL LIKE SalesData; -- to copy the format only from one table to another table
DESC TABLE SALESDATA_FINAL;

CREATE OR REPLACE TABLE SALESDATA_FINAL AS 
SELECT * FROM SalesData; -- to copy all the data from one table to another
select * from SALESDATA_FINAL;

ALTER TABLE SALESDATA_FINAL
ADD COLUMN ORDER_ID1 VARCHAR(15);

ALTER TABLE SALESDATA_FINAL
ADD PRIMARY KEY (ORDER_ID1);

DESCRIBE TABLE SALESDATA_FINAL;
SELECT * FROM SALESDATA_FINAL;

update SALESDATA_FINAL
SET ORDER_ID1 = order_id;

SELECT * FROM SALESDATA_FINAL;

ALTER TABLE SALESDATA_FINAL
DROP ORDER_ID ;

SELECT * FROM SALESDATA_FINAL;

alter table SALESDATA_FINAL
RENAME COLUMN ORDER_ID1 TO ORDER_ID;

DESCRIBE TABLE SALESDATA_FINAL;
SELECT * FROM SALESDATA_FINAL;

SELECT *, 
    CASE 
        WHEN DISCOUNT > '0' THEN 'YES'
        ELSE 'FALSE'
    END AS IF_DISCOUNTED
FROM SALESDATA_FINAL;

SELECT *,
    CASE 
        WHEN PROFIT > '0' THEN 'PROFIT'
        WHEN PROFIT < '0' THEN 'LOSS'
        ELSE 'NO PROFIT NO LOSS'
    END AS PROFIT_LOSS_STATUS
FROM SALESDATA_FINAL;


SELECT *,
    DATEDIFF(DAY, ORDER_DATE, SHIP_DATE) AS DELAY_IN_SHIPMENT,
    CASE
        WHEN DELAY_IN_SHIPMENT <= 3 THEN '5'
        WHEN DELAY_IN_SHIPMENT > 3 AND DELAY_IN_SHIPMENT <= 6 THEN '4'
        WHEN DELAY_IN_SHIPMENT > 6 AND DELAY_IN_SHIPMENT <= 10 THEN '3'
        WHEN DELAY_IN_SHIPMENT > 10 THEN '2'
    END AS SHIPMENT_RATING
FROM SALESDATA_FINAL;



ALTER TABLE SALESDATA_FINAL
ADD COLUMN ID VARCHAR(10);

UPDATE SALESDATA_FINAL
SET ID = SPLIT_PART(ORDER_ID,'-',3);

SELECT * FROM SALESDATA_FINAL;



